### ISSUE TITLE
[Documentation] Setting up a dev environment for eris-cli

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1004]
@zramsay commented on [Sun Mar 06 2016](https://github.com/eris-ltd/coding/issues/4)

from: https://github.com/eris-ltd/eng.erisindustries.com/issues/6

---

@zramsay commented on [Tue Jul 05 2016](https://github.com/eris-ltd/coding/issues/4#issuecomment-230377566)

use the nice docker way rather than the hacky scripts

**Comment by zramsay** [comment]
cc @silasdavis WRT to setting up `vagrant`

**Comment by zramsay** [comment]
`docs/install-source.md` and the `CONTRIBUTING.md` file cover it. The former can evolve to cover "how to get started contributing"
