### ISSUE TITLE
[Chains] Easier method to add users

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1008]
@dennismckinnon commented on [Thu Aug 25 2016](https://github.com/eris-ltd/eris-cm/issues/38)

I have had a few people express confusion on how to maintain a chain through its lifecycle such as adding new users and modifying permissions etc.  Maybe this is a matter of clarifying how to access these components or maybe we need to build nicer fronts to these features IDK

**Comment by zramsay** [comment]
related ish to #1010 (updating chains). added to epic

**Comment by compleatang** [comment]
too much surface area here. closing and we can revisit later if the need actually exists.
