### ISSUE TITLE
[Chains] Create unit tests to satisfy new make paradigm

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1009]
@AFDudley commented on [Thu Aug 11 2016](https://github.com/eris-ltd/eris-cm/issues/34)

Not entirely sure what else to say, but we should discuss it and put it on a roadmap.

---

@benjaminbollen commented on [Mon Aug 29 2016](https://github.com/eris-ltd/eris-cm/issues/34#issuecomment-243134080)

@AFDudley would it make sense to first test the `go test` unit test framework for e-cm, before launching off into the more expensive (in time and infrastructure cost) launch of aws machine that installs docker and pulls the other eris images; for integration / acceptance tests?

---

@benjaminbollen commented on [Mon Aug 29 2016](https://github.com/eris-ltd/eris-cm/issues/34#issuecomment-243135126)

also, it seems the current e-cm testing cycle does not run `go test` :)

eg see: https://circleci.com/gh/eris-ltd/eris-cm/242

---

@AFDudley commented on [Mon Aug 29 2016](https://github.com/eris-ltd/eris-cm/issues/34#issuecomment-243154965)

Yes. We need to run `build_lin` and `test_lin` jobs before running `build_DI` jobs. We then have to run the `test_DI` scripts against a whole ton of configurations.

**Comment by zramsay** [comment]
obsolete / will happen naturally
