### ISSUE TITLE
[Pkgs] Enhance EPM to support working with contract bundles

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1013]
@j-h-scheufen commented on [Tue Apr 05 2016](https://github.com/eris-ltd/eris-pm/issues/106)

When compiling and deploying Solidity contracts via EPM the resolution of import statements does not work in a way that easily allows storing .sol files across multiple directories. The "import" path is always attempted to be resolved relatively to the contract file containing it. This forces a develop to work with relative paths, e.g. `import "../../xyz_bundle/bla/contract.sol"` and obviously this easily brakes and makes contracts not very portable.
With _contract bundles_ downloaded from the Eris Contracts Library there is a default bundles home location (~/.eris/bundles) which can be used as the root to resolve impart paths.
## Requirements

A contract developer should be able to specify a path identifying a contract bundle as

```
import "com/erisindustries/bundleXYZ/bla/contract.sol"
```

and the EPM should follow a more intelligent strategy to locate the required sources for compilation.
## Strategy for resolving import paths (to be reviewed by DEV) in order:
- relative to the directory of the contract file containing the import statement
- relative to the `--contracts-path` parameter (-p), if specified
- relative to the bundles home directory ~/.eris/bundles/

Once an import path can be resolved successfully, it is not 100% clear how to facilitate contract compilation. Out of necessity utility scripts were created in the past, e.g. a Python script by @dennismckinnon that copies all referenced files into a temporary location and amends the import statements in the source files before compiling. I (@j-h-scheufen) had started experimenting with the Solc NPM module as a Node.js utility to read all referenced files into memory and feeding them to the compiler.
Someone familiar with the EPM Go code and the Solc compiler wrapping should weigh in how this can be implemented. I would regard it as a goal if compilation can be achieved without pre-processing / modifying the contract sources, but just in case we know that it's a fallback that works.

Solution discussed in Iceland: solve via path prefix remappings such that a (yet to be defined) key word in the beginning of the import path, e.g. bundle/, would be replaced by solc with the path to the contract_bundles directory in which dependencies were placed.
See http://solidity.readthedocs.io/en/latest/layout-of-source-files.html#paths

---

@VoR0220 commented on [Tue Apr 05 2016](https://github.com/eris-ltd/eris-pm/issues/106#issuecomment-205961160)

I know this is definitely possible with the built from source solidity compiler. But you are correct for the node version. It most definitely does not work there. Been meaning to get on building that. Now I have more of a reason to make that happen. :) 

---

@VoR0220 commented on [Tue Apr 05 2016](https://github.com/eris-ltd/eris-pm/issues/106#issuecomment-205962070)

There is a way to hack this together....I would think it would be preferred not to do that and I think there is most definitely a desire to have this as a feature inherent in solidity. I'll definitely be in discussions with Christian on this one. 

---

@j-h-scheufen commented on [Wed Aug 31 2016](https://github.com/eris-ltd/eris-pm/issues/106#issuecomment-243649745)

Solution discussed in Iceland: solve via path prefix remappings such that a (yet to be defined) key word in the beginning of the import path, e.g. `bundle/`, would be replaced by solc with the path to the `contract_bundles` directory in which dependencies were placed.
See http://solidity.readthedocs.io/en/latest/layout-of-source-files.html#paths

---

@VoR0220 commented on [Wed Aug 31 2016](https://github.com/eris-ltd/eris-pm/issues/106#issuecomment-243650998)

agreed. Don't forget to weigh in on the lock file @j-h-scheufen :)

**Comment by j-h-scheufen** [comment]
Note: Moved implementation requirements of this epic to its own ticket: #1128

**Comment by benjaminbollen** [comment]
initial task break-down proposal in https://github.com/eris-ltd/eris/issues/1124

**Comment by zramsay** [comment]
handled in #1166
