### ISSUE TITLE
[Pkgs] deploy contract with data for constructor arguments fails

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1021]
@pascalverlinden commented on [Wed Sep 28 2016](https://github.com/eris-ltd/eris-pm/issues/227)

I get an error on deployment when I add constructor arguments in my epm.yaml deploy job.

In my epm.yaml file I have the following:
- name: value1
  job:
    set:
      val: 123
- name: deployJob
  job:
    deploy:
      contract: my_contract.sol
      data: $value1
      wait: true
- name: queryValue
  job:
    query-contract:
      destination: $deployJob
      data: getValue
      wait: true
- name: assertValue
  job:
    assert:
      key: $queryValue
      relation: eq
      val: $value1
      wait: true

When using eris pkgs do --chain mychain --address $addr
the contract gets deployed at address X
but on executing the queryValue job, it gives the following message:
Account X does not exist (with X the address above)

When I leave out the data portion in the yaml, and if I call my contract's functions to set the value and test it from the yaml, it works fine.

So, what am I doing wrong?

I am using the following versions:
- [ 1.11.1, build 5604cbe ] `docker version`
- [Eris CLI Version: 0.11.4 ] `eris version`
- [Ubuntu 14.04.3 LTS ] operating system details (osx/windows/linux)

Thanks for helping!

**Comment by zramsay** [comment]
@pascalverlinden are you still having this issue (it was moved from the to-be-deprecated eris-pm repo) ?
@VoR0220 are you able to reproduce?

**Comment by VoR0220** [comment]
This is a 0.11.4 error...that should be taken into account.

**Comment by pascalverlinden** [comment]
Hello,

sorry for my late reply. I use a workaround for the time being, didn't check it anymore. I’ll test this with the new version.

Thanks!
Pascal

**Comment by VoR0220** [comment]
Closing as long been resolved.
