### ISSUE TITLE
[Pkgs] Have Set Job Come from an empty interface

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1022]
@VoR0220 commented on [Mon Oct 10 2016](https://github.com/eris-ltd/eris-pm/issues/241)

Problem: `true` sets to 1, not to bool value `true` and this causes confusion in our assert jobs. Small fry, but fixing this will enable a better UX. 

Other solution: Perhaps pass values instead into assert jobs and somehow assert that the values are the same? (might be more pain than it's worth).

**Comment by zramsay** [comment]
obsolete / not well defined
