### ISSUE TITLE
[Pkgs] Run a single job called by name

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1023]
@compleatang commented on [Wed Sep 28 2016](https://github.com/eris-ltd/eris-pm/issues/228)

**Problem** -- sometimes users want to walk through a jobs series. To do this they sometimes want to simply call a single job and run that.

**Solution** -- add a `--job` flag (which defaults to `all`) that can be utilized.

**Comment by zramsay** [comment]
technical debt & more of a nice-to-have-but-probably-will-never-be-used feature
