### ISSUE TITLE
[Pkgs] Smart Gas

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1032]
@VoR0220 commented on [Fri May 13 2016](https://github.com/eris-ltd/eris-pm/issues/127)

Most frameworks with solidity have a problem whereby users are essentially guess and checking how much gas they need to input into transaction. I think we have the capability to automate this with the help of the epm.yaml file. We can run a dry run through the epm.yaml jobs and get a much more accurate estimation of how much gas will actually cost an ethereum user based on the inputs of current gas price plus the unknown factors (how many loops are you going to go through...how long are your strings going to be...how long will your arrays get)? After that, we can input the estimated gas, ask them if they're sure they want to deploy live, and then deploy at the more accurate gas amount....no guesswork needed. 

---

@compleatang commented on [Sat Jul 09 2016](https://github.com/eris-ltd/eris-pm/issues/127#issuecomment-231532441)

This is a good feature. However, when we make feature requests for ourselves we need to do in **Problem** // **Solution** format. Just because everybody else does it isnt' a good problem for the record...

**Comment by zramsay** [comment]
not part of direction of platform
