### ISSUE TITLE
[Pkgs] Support multiple output files for EPM pkgs command

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1033]
Migrated from https://github.com/eris-ltd/eris-pm/issues/195

@j-h-scheufen commented on Wed Aug 17 2016

The change implemented in https://github.com/eris-ltd/eris-pm/issues/176 does not go far enough to support the needs of users who manage their epm jobs in multiple files. Currently EPM supports the `-f` flag which allows users to organize their jobs across multiple files; this is very useful and a requirement for bundles deployment, e.g. to be able to deploy contracts in separate phases, like libraries. However, it is currently not possible to control the output file and as far as I can see, the `jobs_output.json` would be overwritten on sequential jobs invocation.
## Requirements
1. Change the default behavior to use the input filename as a template for the output. `-f MyJobs.yaml` would result in `MyJobs.output.json`. Similarly `MyJobs.epm.yaml` -> `MyJobs.epm.output.json`. (exact logic to be specified)
2. Provide a commandline flag to control the output file name. There currently is a flag `-o`, but its description is unclear and it does not seem to be addressing this requirement.

**Comment by compleatang** [comment]
closing for now. we are going to need to refactor how we track state at a later date.

**Comment by zramsay** [comment]
tests are captured here: https://github.com/monax/cli/blob/issue-1033-multiple-jobs-output-files/tests/test_runner.sh#L115-L190

@j-h-scheufen let me know if these cover it

**Comment by j-h-scheufen** [comment]
@zramsay Tests look good and functionality is adequate. I wish, though, my suggestion to use the input file's name automatically as the output name would've been taken up as I had described in this ticket. It would make this so much easier as it saves typing the `--output` option for 99% of the cases when someone has multiple yaml files. Is this still worth considering? The UX would be so much improved!

**Comment by zramsay** [comment]
this is merged on develop branch
