### ISSUE TITLE
[Pkgs] Redo PreProcess function

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1034]
@VoR0220 commented on [Fri May 20 2016](https://github.com/eris-ltd/eris-pm/issues/136)

Reasons to do this:

a) it's ugly as sin
b) it's inefficient, I think we might do better with a string map
c) it's very difficult to determine what is going on in the function, even from someone who has dissected it before. 

---

@compleatang commented on [Mon Aug 22 2016](https://github.com/eris-ltd/eris-pm/issues/136#issuecomment-241495122)

can we close this?

---

@VoR0220 commented on [Mon Aug 22 2016](https://github.com/eris-ltd/eris-pm/issues/136#issuecomment-241497416)

no not yet. It is still very much a todo.

**Comment by zramsay** [comment]
happens in #1323
