### ISSUE TITLE
[core] After a docker-machine restart, an existing chain cannot be started

### ISSUE THREAD

**Issue by j-h-scheufen** [monax/cli#1070]
Eris version: 0.12.0

After restarting docker-machine, a previously running chain cannot be started again with `eris chains start`. Error message:
```
Docker: {"message":"Cannot link to a non running container: /keys-8e3aed27-d25e-4ee1-88ba-ea8d0fe86eb2 AS /allianz-55c2da88-4af7-496c-bfdf-b24b6ad78bb2/keys"}
```
The current workaround is to throw it away and recreate it.

**Comment by pietv** [comment]
@j-h-scheufen thanks for logging it, will try to reproduce. Your Docker host is in the VirtualBox, right?

**Comment by zramsay** [comment]
@j-h-scheufen are you still experience this?

**Comment by zramsay** [comment]
does not appear to be a blocker / fix might be to start keys prior to restarting a chain

**Comment by cbruguera** [comment]
I'm getting this error as well. Running on Linux, so there's no "docker-machine", just Docker.

@zramsay By "starting keys" I assume you mean the "keys" service?... I'm doing this, along with the "compilers" service (both were stopped), for some reason the compilers service doesn't seem to start (star isn't shown on `monax services ls`... Now I try starting the chain again, and there's no error shown (no feedback at all in fact), so I assume it works now, but there isn't a star under "ON" on `monax chains ls` either, so I don't know if the chain starts or not, I assume it doesn't.

Any idea?
