### ISSUE TITLE
[Pkgs] Add Compile Job for Simple JS interaction

### ISSUE THREAD

**Issue by VoR0220** [monax/cli#1076]
Sequester compiling into its own job for the purpose of javascript interaction based on the jobs output file.

**Comment by compleatang** [comment]
Compile job should simply write contract.bin and abi/ContractName to disk in appropriate locations. Given that epm already parses bin files and deploys them successfully as well as javascript libs interactions this will be a nice feature for many users (including us who need to distribute binaries and abis).

**Comment by j-h-scheufen** [comment]
@VoR0220 please add the library/bundles label

**Comment by zramsay** [comment]
is this part of #1323?

**Comment by VoR0220** [comment]
yuppers

**Comment by zramsay** [comment]
JS interaction no longer part of the stack
