### ISSUE TITLE
[Core] create a wizard package & add an interactive command line to pm

### ISSUE THREAD

**Issue by VoR0220** [monax/cli#1118]
* Problem: Interactive command lines (Wizards) I think are going to be very helpful in establishing good command line tools. It is thus preferable that they get their own package so as to be more useful in describing the package being used. 

* Solution: Create a package purely for command line interactive inputs. Furthermore, since all of our wizards are marmot related, I believe the package should be named "Marmots" and possibly branch from there if needed.

**Comment by zramsay** [comment]
not part of the direction of the platform

**Comment by VoR0220** [comment]
How?
