### ISSUE TITLE
Implement package management

### ISSUE THREAD

**Issue by VoR0220** [monax/cli#1124]
Checklist:
- [ ] Create manifest json structure
- [ ] Create lock file json structure
- [ ] Have jobs easily interact with package manager (and potentially even be a part of it)
- [ ] be able to reliably relay information on state of the contract at this time (for linking)

**Comment by compleatang** [comment]
note have narrowed the checklist here tremendously.

for 0.18.0 we will assume that the files exist locally. the package management functions of monax tool need to be focused on dependency tree resolution within the host's file system -> linking -> deploying -> linking -> deploying -> ....

this issue needs to be made into an epic with all of the little package management issues rolled into this epic. anything which does not have to do with the checklist above needs to then be closed off. 

note that we are significantly narrowing the surface area of what the monax tool will do.
