### ISSUE TITLE
[Core] Remove `--machine` flag

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1150]
**Problem** -- Docker machines are a very expensive abstraction for nominal (if any gain). Why?

*Costs*

* this is a docker only, not openly maintained API surface that we need to maintain. 
* the various networking layers are ridiculous (see, accessing keys for a remote docker machine)
* volume feature basically becomes ridiculous (see, our excessive use of data containers where simple volumes should do)

*Gains*

* if "feels" neat....?

**Solution** - stop supporting docker on remote machines. Benefits of this approach:

* reduced surface area on a third-party API/abstraction
* increased ability to migrate to rkt or to other container management systems

**Constraints** -- currently we need to natively support windows, osx and docker's native engines for those operating systems need to come out of beta.

**Comment by VoR0220** [comment]
when you say "stop supporting on remote machines" you mean that we won't support someone creating a machine not named "eris" and work from there? Or do you mean that we won't support the docker-machine at all? Because the latter kills docker for mac and I believe for Windows. Which hurts our userbase.

**Comment by zramsay** [comment]
let's drop. "feels neat" is not enough of an argument to keep around the complexity. maybe we poll users in the Den?

**Comment by pietv** [comment]
we don't have good tests for this, so I'd vote for dropping it too.

**Comment by VoR0220** [comment]
I need clarification before my vote goes in.

**Comment by compleatang** [comment]
@VoR0220 read the final paragraph.

**Comment by VoR0220** [comment]
ahhhhhh...so Docker does plan to support these natively (I don't follow Docker enough to know). If so, absolutely in favor of dropping.

**Comment by zramsay** [comment]
re-labelling since it looks like we decided to drop this flag:
:( but for the better

**Comment by pietv** [comment]
@zramsay @VoR0220 @compleatang to avoid confusion, i'd like to vote for keeping automatic Docker Machine parameters detection via environment variables, but dropping the `--machine` flag to reduce complexity.

**Comment by compleatang** [comment]
@pietv I'm on board with that. It's gonna be a while before DFW and DFM are fully operational.
