### ISSUE TITLE
Eris CLI outputs CRLF line terminators which has dramatic results on terminal

### ISSUE THREAD

**Issue by silasdavis** [monax/cli#1168]
Running on Linux with eris 0.12.0. I came across some very weird behaviour trying to script around eris-keys
```bash
#!/bin/bash
genAddr=`eris keys gen`
echo "$HOME/.eris/keys/data/${genAddr}/${genAddr}"
```

produces:

```
/FB06549B7B5BB98BA4EFA90E82B5D1AD910DE95A98BA4EFA90E82B5D1AD910DE95A
```

Hm. Odd.

Compiling and running eris-keys locally (not through docker/CLI):

```bash
#!/bin/bash
genAddr=`eris-keys gen --no-pass`
echo "$HOME/.eris/keys/data/${genAddr}/${genAddr}"
```

Gives expected result:

```
/home/silas/.eris/keys/data/728B83A276E19E0712180DC39F07E187AB6C03F7/728B83A276E19E0712180DC39F07E187AB6C03F7
```

After much puzzling, I found that:

```bash
eris keys gen | file -
/dev/stdin: ASCII text, with CRLF line terminators
```

and lo trimming the ctrl and line feed characters:

```bash
#!/bin/bash
genAddr=`eris keys gen | tr -d '\015\012'`
echo "$HOME/.eris/keys/data/${genAddr}/${genAddr}"
```

Fixes the output:

```
/home/silas/.eris/keys/data/6CC8143245F2A9BA61AD88B697E5B42CAC1B04CB/6CC8143245F2A9BA61AD88B697E5B42CAC1B04CB
```

What appears to happen is that the bash substitution works with a circular 1-line buffer (or something to that effect) and the trailing carriage return CRLF causes output to overwrite the beginning of the buffer.

So I think the answer is to follow the POSIX standard and terminate with EOF (and for eris keys since there is a single record this should be NEWLINE,EOF).

**Comment by zramsay** [comment]
we should not devote resources to solving this issue
