### ISSUE TITLE
[PM/Loaders] Redo loaders tests for PM w/ better error handling

### ISSUE THREAD

**Issue by VoR0220** [monax/cli#1173]
Problem: Loaders tests for packages are outdated and even with a quick fix don't really test what they should be testing. 

Solution: Write new and refreshed tests for PM loading.

**Comment by zramsay** [comment]
updated title to include #1172

**Comment by benjaminbollen** [comment]
Does this ticket both cover the implementation and the tests for that implementation?

**Comment by VoR0220** [comment]
Apparently so.

**Comment by zramsay** [comment]
handled in #1323 (nice work there)
