### ISSUE TITLE
Full Node Terminal becomes unresponsive after 3-4 days

### ISSUE THREAD

**Issue by andytudhope** [monax/cli#1185]
- [1.12.5] `docker version`
- [0.12] `eris version` and [0.12.1] `eris-db`
- [Mac OS Sierra 10.12.2] operating system details

After 3-4 days of running a simple chain with 4 nodes: 1 full node on an iMac, and 3 validators on Ubuntu VMs on a local server, the chain continues to run and I can still interact with it from my node app, but the full node (Mac) terminal becomes entirely unresponsive. `eris chains ls`, `eris chains logs -f <chain_name>`, `eris keys ls` - nothing works. My latest tests include running `logrotate` on every node (which interestingly, seems to have slowed down block production by about half, but has made no difference to this issue).

It's difficult to debug because I can't see the logs, but here are the logs printed out from one of the VMs:

```
INFO[01-27|04:17:00] HTTPRestRPC                              module=rpcserver method=/status args=[] returns="[<types.ErisDBResult Value> <error Value>]"
INFO[01-27|04:17:00] Served RPC HTTP response                 module=rpcserver method=GET url=/status status=200 duration=0 remoteAddr=10.10.1.211:51897
INFO[01-27|04:17:00] Served RPC HTTP response                 module=rpcserver method=GET url=/favicon.ico status=200 duration=0 remoteAddr=10.10.1.211:51897
INFO[01-27|04:17:08] Receive                                  module=consensus src="Peer{MConn{10.10.1.211:46656} DF51166B6E8C out}" chId=20 msg="[HasVote VI:1 V:{32207/00/1} VI:1]"
INFO[01-27|04:17:08] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{10.10.1.211:46656} DF51166B6E8C out}" peerRound=0 height=32207 round=0 prevotes=BA{4:_X_X} index=1
INFO[01-27|04:17:08] Receive                                  module=consensus src="Peer{MConn{10.10.1.211:46656} DF51166B6E8C out}" chId=20 msg="[HasVote VI:3 V:{32207/00/1} VI:3]"
INFO[01-27|04:17:08] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{10.10.1.211:46656} DF51166B6E8C out}" peerRound=0 height=32207 round=0 prevotes=BA{4:_X_X} index=3
INFO[01-27|04:18:03] Receive                                  module=consensus src="Peer{MConn{10.10.1.211:46656} DF51166B6E8C out}" chId=20 msg="[NewRoundStep H:32207 R:0 S:RoundStepPropose LCR:0]"
```

**Comment by zramsay** [comment]
thanks for bug report Andy. This is definitely not expected. We'll investigate further but it may take time to ferret out given nature of bug. Looks like it could be related to #612

**Comment by zramsay** [comment]
this is suspected to be a memory leak. once that is solved, we'll revisit this issue

**Comment by compleatang** [comment]
Closing here. Please report burrow runtime problems to hyperledger/burrow .
