### ISSUE TITLE
[Services] migrate from `quay.io/eris/ipfs` to `ipfs/go-ipfs`

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1199]
Our docker image isn't automatically built. There's is.

**Comment by zramsay** [comment]
replaces #742

**Comment by VoR0220** [comment]
Going to require a breaking down of the current paradigm of how we default pull images and configure them. On this note, do you think it might be wise to merge together `config` and `initialize` @zramsay ?

**Comment by zramsay** [comment]
not _really_; it will require slight modification to `version/images.go` as well as init

**Comment by VoR0220** [comment]
I'm not sure I agree. The default registry variable is fairly invasive throughout the packages atleast on my first look through (though to be fair, you definitely have a better understanding of the packages), and that needs to be handled in a way whereby it can be swappable and replaceable. We should standardize and say "These are monax images, these are other images" and create from there.

**Comment by zramsay** [comment]
we just need to changed the logic in https://github.com/eris-ltd/eris/blob/develop/initialize/initialize.go#L144-L151

**Comment by VoR0220** [comment]
Good to know

**Comment by zramsay** [comment]
replaced by  #1306, rip ipfs
