### ISSUE TITLE
Error compiling contracts

### ISSUE THREAD

**Issue by ramilexe** [monax/cli#1232]
Please include in your bug report:

- [ ] `docker version`

```Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
```

- [ ] `eris version`
`Eris CLI Version: 0.12.0 (002c63e)`

- [ ] operating system details (osx/windows/linux)
`Ubuntu 14.04.5 LTS`
- [ ] what you expected to happen
A contract to be compiled without errors
- [ ] what actually happened

```
failed to send HTTP request Post https://compilers.monax.io:10120: dial tcp: lookup compilers.monax.io on 8.8.8.8:53: no such host
Error compiling contracts: Compilers error:
Post https://compilers.monax.io:10120: dial tcp: lookup compilers.monax.io on 8.8.8.8:53: no such host

Could not perform pkg action service: Could not perform pkg action: Container interactive-66683175-2905-44d7-960a-e1f84d8d4fa4 exited with status 1
```

**Comment by VoR0220** [comment]
Will examine this. In the meantime, use the `-z` flag to use a local compiler service. Much more reliable and what we will be defaulting to in `0.16.0`.

**Comment by zramsay** [comment]
solved based on the two :+1: given to @VoR0220 's answer. @ramilexe please re-open if this is still an issue
