### ISSUE TITLE
contract is not deploying in chain and not showing any error also

### ISSUE THREAD

**Issue by NodeGuy** [monax/cli#1258]
Moved from https://github.com/eris-ltd/eris-contracts.js/issues/72.

# Version Numbers

Fill in version numbers below.

* Node.js: v7.4.0
* Eris CLI: 0.12.0
* eris-contracts: 

# Issue Description

i have created a chain with 1:root, 1:full and 2:validator nodes. my chain is working fine. but when I am trying to deploy my contract using eris pkgs do --chain [chain_name] --address [node_account_address].
only default address is executing in the job and process end without deploying the contract and without any error. 
I have no idea why it is not deploying. Am I making any wrong .yaml file or .sol file?? kindly help.
# yaml file I have created to deploy my contract is:
jobs:

- name: deployK0
  job:
    deploy:
      contract: structs0.sol
      instance: Structs0
      wait: true

- name: addThing0
  job:
    call:
      destination: $deployK0
      function: addThing
      data:
        - selling_tomato
        - sellingTomato
        - tomatofilehash
        - tomatofilename
      wait: true

- name: assertTen0
  job:
    assert:
      key: $addThing0
      relation: eq
      val: 10

- name: checkDesc0
  job:
    query-contract:
      destination: $deployK0
      function: getDesc

- name: assertDesc0
  job:
    assert:
      key: $checkDesc0
      relation: eq
      val: selling_tomato

- name: checkUrl0
  job:
    query-contract:
      destination: $deployK0
      function: getUrl

- name: assertUrl0
  job:
    assert:
      key: $checkUrl0
      relation: eq
      val: sellingTomato

- name: checkHash0
  job:
    query-contract:
      destination: $deployK0
      function: getHash

- name: assertHash0
  job:
    assert:
      key: $checkHash0
      relation: eq
      val: tomatofilehash

- name: checkName0
  job:
    query-contract:
      destination: $deployK0
      function: getName

- name: assertName0
  job:
    assert:
      key: $checkName0
      relation: eq
      val: tomatofilename

Include all code and data needed to reproduce the problem by replacing the examples below.

## Solidity file structs0.sol :

contract Structs0 {
    struct Thing {
        address thingMaker;
        string description;
        bytes32 url;
        bytes32 filehash;
        string filename;
    }

    Thing[] things;

    function addThing(string description, bytes32 url, bytes32 filehash, string filename) returns (uint) {
        things.push(Thing(msg.sender, description, url, filehash, filename));
        return 10;
    }

    function getDesc() returns(string description) {
        return things[0].description;
    }

    function getUrl() returns(bytes32 url) {
        return things[0].url;
    }

    function getHash() returns(bytes32 filehash) {
        return things[0].filehash;
    }

    function getName() returns(string filename) {
        return things[0].filename;
    }
}

the output it is showing after running eris pkgs do is:

user1@user1:~/.eris/apps/appStruct$ eris pkgs do --chain datachain --address 5149874569DA23FB2F527C1EFC37B089B4369182
Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
user1@user1:~/.eris/apps/appStruct$

**Comment by zramsay** [comment]
no response from the original user who opened the issue
