### ISSUE TITLE
[Chains] Harmonize `chains make --output` options

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1273]
**Problem**  -- `--zip` `--tar` are unnecessary cognitive overhead (also there is #1272). 

**Solution** -- These should all be combined into a string slice flag called `--output` which should contain the following nonexclusive options (once #1272 is shipped):

* `std` - display output on standard out (` ! --quiet`)
* `zip` - write zip files
* `tar` - write tarballs
* `kubernetes` - write k8s config files

**Comment by zramsay** [comment]
didn't need `std` -> that's just the default (no flag given). closed in #1340
