### ISSUE TITLE
`eris pkgs do` fails to use existing compilers container after restart

### ISSUE THREAD

**Issue by silasdavis** [monax/cli#1282]
This is an issue on the current release-0.16 branch. It seems if you restart docker (as when you restart your machine) then cli will try to reuse any previously created compilers container, but the compilers container will fail. The workaround is to remove any old compilers containers with `docker rm`

### Reproduction
1. Make a chain
2. Start it
3. Deploy any contract (which will work fine)
4. `systemctl restart docker` or whatever
5. `eris services start keys`
6. `eris chains start foo`
7. `eris pkgs do ...` (edited)

Then the compilers container will be started but will immediately fail leading to:

```
Job Name                                      deployGSFactory
failed to send HTTP request Post http://172.17.0.4:9099: dial tcp 172.17.0.4:9099: getsockopt: no route to host
Error compiling contracts: Compilers error:
Post http://172.17.0.4:9099: dial tcp 172.17.0.4:9099: getsockopt: no route to host
```

Looking at the compiler container logs you will see:

 ```
Hello I'm the marmots' compilers server
problem starting binaries directory, exiting...
```

The error originates here: https://github.com/monax/compilers/blob/release-0.16/perform/server.go#L20. Unfortunately it does not report the actual error (it should), but perhaps the directory already exists. I'm not sure how the restarting of docker leads to this failed re-initialisation of the server (since the container is stopped but has run previously). Is the service being booted twice?

**Comment by zramsay** [comment]
needs to be handled in #1323

**Comment by zramsay** [comment]
more specifically to the previous comment (and after discussion this morning), this won't apply after #1323

**Comment by zramsay** [comment]
fixed in https://github.com/monax/compilers/pull/135 (suspected)
