### ISSUE TITLE
[chains/keys] - Make a chain cache

### ISSUE THREAD

**Issue by VoR0220** [monax/cli#1325]
Feature idea for a method with which to best implement chain "checkouts" and integrate them seemlessly through package management and keys usage. 

## Problem we have with chain checkouts -
1. While they may seem like just a nice feature to have, they do provide value in the form of organization of workflow in the cli and definitely help the overall UI.

2. This is a really useful feature for users and helps with package management efforts by implementing your "mark" on a chain lock file. 

## How do we go about implementing:

1. The general design of this is in the form of a stack with the methods: push, pops and switch. We implement this using a simple global variable for an array of burrow NodeClient/KeyClient combos, embedded in the type that holds them (lets call them ChainDeps for now). 

2. Whenever they want to checkout, we switch to the containerID they are at. This could be set in the monax.toml being what container id to name/containerID/ChainDep, though it might be problematic if someone kills something in docker. Kubernetes could help solve this problem by making chains into a cluster that we can start up and boot up in groupings and ordering from there what gets killed and what doesn't get killed. We should look into potentially [using it](https://github.com/kubernetes/client-go) cc @zramsay 

## Testing:
- different combinations of swapping keys through different chains
- different combinations of swapping job runnings through different chains to test that state remains the same throughout it

**Comment by zramsay** [comment]
this issue does not address a specific problem & the chains/keys checkout feature is handled in issues already (still up for discussion what priority each feature is)
