### ISSUE TITLE
[docs] update and test the app.js

### ISSUE THREAD

**Issue by zramsay** [monax/cli#1332]
The file located here https://github.com/monax/cli/blob/develop/docs/contracts_simple_idi/app.js is part of the tutorial series on the website. A user has reported in Slack that it throws an unhandled promise. A newer but never assimilated version of a similar app can be found [here](https://gist.github.com/zramsay/f5d179c0320ba442dc03e0ae6757be74) which does not throw an unhandled promise. Either the old version should be fixed or it should be replaced with the new version. Ideally, both files can be added since they're nice introductions to javascript. Regardless, at least one of them needs to be tested; the ability to run `npm test` should be added to the `contracts_simple_idi` directory.

**Comment by NodeGuy** [comment]
I'm blocked by https://github.com/monax/cli/issues/1337.

**Comment by NodeGuy** [comment]
I'm blocked by https://github.com/monax/legacy-contracts.js/issues/89.

**Comment by NodeGuy** [comment]
https://github.com/monax/legacy-contracts.js/issues/89 was fixed but then I was blocked by https://github.com/monax/cli/issues/1337.  Silas gave me a potential workaround today but I'm not going to have time to complete this.
