### ISSUE TITLE
[chains] make --init-dir less necessary for chain starting and more user friendly

### ISSUE THREAD

**Issue by VoR0220** [monax/cli#1341]
Problem:

It's cumbersome to have to go to the monax root directory and find the directory with all the chain information, and also can create something of a disorganized repository with having to move the files manually. 

Solution:

create a `dir` flag that states where the files should be deployed to in the case of a make. In addition add in a way to automatically search and find an account to start the node from with a preference from participant to root to start the chain.

**Comment by zramsay** [comment]
overruled by baus marmot
