### ISSUE TITLE
migration of apt-get repository and installation of the cli tool

### ISSUE THREAD

**Issue by test2015deve** [monax/cli#1354]
Hi,

I'm trying to install Eris platform by using commands below. But I got the erros like "**Could not resolve host: apt.monax.io"**

	_sudo add-apt-repository https://apt.monax.io
	curl -L https://apt.monax.io/APT-GPG-KEY | sudo apt-key add -
	sudo apt-get update && sudo apt-get install -y eris_

Is there any problem on your repository? Why do not we reach? 

Thanks

**Comment by compleatang** [comment]
Please note that the eris command is no longer.

The apt-get instructions for the new repository for the `monax` tool are here:

```
sudo add-apt-repository https://pkgs.monax.io/apt
curl -L https://pkgs.monax.io/apt/APT-GPG-KEY | sudo apt-key add -
sudo apt-get update && sudo apt-get install -y monax
```
