### ISSUE TITLE
New getting started documentation

### ISSUE THREAD

**Issue by test2015deve** [monax/cli#1355]
Hi, 

On this issue:  #1354, you said that there are some changes on the commands because of the migration works 

I've used the getting started page _(https://monax.io/docs/tutorials/getting-started/)_ to install before. Is there any changes for the installation getting started document(except command changes eris --> monax) or is the same? 

Thank you

**Comment by compleatang** [comment]
just `s/eris/monax/g` ... we're getting the tut finalized very shortly.

**Comment by compleatang** [comment]
please note that the file location has moved to ->  https://monax.io/docs/getting-started/

**Comment by compleatang** [comment]
we have a redirect now so that the old getting started page should not load.

**Comment by test2015deve** [comment]
Thank you for your redirection.
