### ISSUE TITLE
Error compiling contract

### ISSUE THREAD

**Issue by vineetchawla** [monax/cli#1360]
Please include in your bug report:

- [ 17.04.0-ce, build 4845c56] `docker version`
- [0.16.0 ] `eris version`
- [ ] `go version` (if applicable)
- [ 0.10.0, build 76ed2a6] `docker-machine version` (if applicable / !linux)
- [ MAC sierra 10.12.4] operating system details (osx/windows/linux)
- [ Contract to be compiled] what you expected to happen
- [failed to send HTTP request Post http://192.168.99.100:9099: dial tcp 192.168.99.100:9099: getsockopt: connection refused
Error compiling contracts: Compilers error:
Post http://192.168.99.100:9099: dial tcp 192.168.99.100:9099: getsockopt: connection refused
]what actually happened

The issue seems very similar to #1232 . But as you guys have already defaulted to local compiler, this should not be considered same issue. Still I tried to add a local compiler flag but the issue remained same. I was just following the tutorial and have done exactly the same as describer in the tutorials.

![screen shot 2017-04-22 at 16 43 34](https://cloud.githubusercontent.com/assets/1390884/25305414/e798f176-277a-11e7-8b99-49cdf3632b37.png)
![screen shot 2017-04-22 at 16 43 54](https://cloud.githubusercontent.com/assets/1390884/25305415/eccde200-277a-11e7-8148-61a74b905087.png)

**Comment by zramsay** [comment]
see this comment for the fix https://github.com/monax/cli/issues/1358#issuecomment-295866561

**Comment by vineetchawla** [comment]
Thanks for such a quick reply on a Saturday. Unfortunately it didn't fix the issue. The error stays exactly the same even though I stopped and started the compiler service after making the changes.  

![screen shot 2017-04-22 at 17 26 09](https://cloud.githubusercontent.com/assets/1390884/25305673/142aab12-2780-11e7-8212-580204668ba3.png)

![screen shot 2017-04-22 at 17 29 23](https://cloud.githubusercontent.com/assets/1390884/25305701/6cdad228-2780-11e7-86bc-bb2e5340b1d3.png)

**Comment by zramsay** [comment]
can you `monax services rm --force --data compilers` and start over

**Comment by vineetchawla** [comment]
Did a monax -yx clean and the command you gave, and created the chain again. Still same error.

**Comment by zramsay** [comment]
hm, i can't think of anything else other than a bug in docker/docker-machine. The fix worked in #1358

**Comment by vineetchawla** [comment]
Would you like any more logs or config settings from my machine?

**Comment by zramsay** [comment]
not  sure what would help. try restarting your computer / docker

**Comment by vineetchawla** [comment]
Wanted to add that I created a new instance on aws, ubuntu 14. The tutorial works perfectly. So on my mac I removed everything, reinstalled, rewrote code and rebooted my laptop, still the same error.

**Comment by VoR0220** [comment]
Are you running through Docker for Mac or Docker machine?

**Comment by vineetchawla** [comment]
Docker machine

**Comment by VoR0220** [comment]
interesting. I'm curious whether or not you can get it working with DFM. Would you mind trying it with DFM? I know we say that we don't "officially" support it but I dev with DFM on my mac.

**Comment by zramsay** [comment]
closing as unresponsive / handled in #1282
