### ISSUE TITLE
Urgent : Burrow error and request for new getting started documentation

### ISSUE THREAD

**Issue by test2015deve** [monax/cli#1361]
Hi there,

- [preferred ] `docker version`
- [0.16.0] `eris version`
- [no] `go version` (if applicable)
- [no] `docker-machine version` (if applicable / !linux)
- [ubuntu] operating system details (osx/windows/linux)
- [ Im getting buffer error ] what actually happened

**Problem:**

Im trying to set up a basic blockchain with version 0.16.0. 

I set up blockchain with the commands as below
**monax chains make --account-types=Full:1  --unsafe**

and ıt was successful and ı checked with logs.

And then, I wanted to write a smart contract and call it from node.js application by using getting started documentation.

But Im getting error seen as below. I think there is more actions that is must be done in addition to last version 0.12.0. Because when i tried many times on last version, ı used to be succesfull.

1- Do you have new getting started documentation?
2- Why ım getting this Burrow error? what should i do? 

Thank you for help

_Burrow error:  Call of method "transactAndHold" with parameters { priv_key: '37CE4983B5CDF91D52355820B93931EFF823BD22754FC7DF481D893458B7625FB1FCAEA618C01C052F145CB2D8F3F46D79F5673E0EF5BFD7375B9BC7CCFBF1B5',
  address: '5AC80AA2E48DD441FDC3F4E124DBF9170AB25A8B',
  data: '60fe47b10000000000000000000000000000000000000000000000000000000000000002',
  gas_limit: 1000000,
  fee: 0 } responded with "Error when transacting: Invalid jump dest".
{ Error: Error when transacting: Invalid jump dest
    at values.next.then (/root/.monax/apps/idi/node_modules/@nodeguy/json-rpc/lib/index.js:16:30)
  method: 'transactAndHold',
  params:
   [ { priv_key: '37CE4983B5CDF91D52355820B93931EFF823BD22754FC7DF481D893458B7625FB1FCAEA618C01C052F145CB2D8F3F46D79F5673E0EF5BFD7375B9BC7CCFBF1B5',
       address: '5AC80AA2E48DD441FDC3F4E124DBF9170AB25A8B',
       data: '60fe47b10000000000000000000000000000000000000000000000000000000000000002',
       gas_limit: 1000000,
       fee: 0 } ],
  code: -32603,
  message: 'Error when transacting: Invalid jump dest' }
(node:6126) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error when transacting: Invalid jump dest
(node:6126) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._

**Comment by zramsay** [comment]
this is an issue in the javascript libraries that is tracked here: https://github.com/monax/legacy-contracts.js/issues/89
