### ISSUE TITLE
Old eris version (0.12.0)

### ISSUE THREAD

**Issue by test2015deve** [monax/cli#1362]
Hi, 

I have some problmes with new version of monax (0.16.0). Instead of this version, I want to use previous version (0.12.0) for now. Is there any way to download previous versions files? What can i do to dowlonad it? 

When I use this commands, I get the error. 

Version 0.12.0

__sudo add-apt-repository https://apt.monax.io
curl -L https://apt.monax.io/APT-GPG-KEY | sudo apt-key add -
sudo apt-get update && sudo apt-get install -y eris__

In previous issues, when ı get this error. You sent me these commands of new version as below. But it is new version. I want to use 0.12.0 version which ı have no any problem to set up and launch an application

Version 0.16.0

_sudo add-apt-repository https://pkgs.monax.io/apt
curl -L https://pkgs.monax.io/apt/APT-GPG-KEY | sudo apt-key add -
sudo apt-get update && sudo apt-get install -y monax_

**Comment by compleatang** [comment]
`apt.monax.io` is no longer supported. as you note `pkgs.monax.io/apt` is now the viable end point for the current release of monax. previous versions of monax can be found on the github releases page. Here's the one for 0.12.0 -> https://github.com/monax/cli/releases/tag/v0.12.0 (note that it was still `eris` for that previous version)
