### ISSUE TITLE
[chains] on chains ls add a field displayed for chainID, genesis hash, and chain name

### ISSUE THREAD

**Issue by VoR0220** [monax/cli#1371]
Problem: 
Users need to know what EXACT chains are online currently and what exactly they are working with for coordination of 1000s of chains. 

Solution:
Display the necessary information in a `chains ls` command. The method needed to gather the required information can be found here: https://github.com/hyperledger/burrow/blob/master/client/node_client.go#L154

**Comment by zramsay** [comment]
`chains ls` has been removed (see #1350)
