### ISSUE TITLE
403 Forbidden while installing monax

### ISSUE THREAD

**Issue by prashb94** [monax/cli#1372]
- [x] `docker version` -  17.03.1-ce
- [x] `eris version` - N/A
- [x] operating system details -  Ubuntu 16.04.2 LTS
- [x] what you expected to happen - Install monax
- [x] what actually happened - 403 Forbidden error while fetching binaries
- [x] steps to reproduction - Following the tutorial on monax.io

sudo add-apt-repository https://pkgs.monax.io/apt
curl -L https://pkgs.monax.io/apt/APT-GPG-KEY | sudo apt-key add -
sudo apt-get update && sudo apt-get install -y monax

The installation just doesn't go through. 
Error - Failed to fetch https://pkgs.monax.io/dists/xenial/main/binary-amd64/Packages  403  Forbidden

**Comment by compleatang** [comment]
I'm unable to reproduce on multiple xenial machines.
