### ISSUE TITLE
[Feature/Jobs] Add checkout chain job 

### ISSUE THREAD

**Issue by VoR0220** [monax/cli#1374]
Problem: Need to change chain midway through jobs file to deploy contract to a separate chain (hyperledger lets say); I need to be able to change the URL, chain ID, and make sure that the key server aligns with it.

Solution:
Add a "checkoutChain" job to allow this to be done as a job that will change the NodeClient and KeyClient settings in the interfaced jobset.

**Comment by zramsay** [comment]
this has not been requested by a user, has no well-defined use case, and would require the plethora of other issues to be implemented prior to yourself tackling it
