### ISSUE TITLE
Help for the deployment smart contract

### ISSUE THREAD

**Issue by devfka** [monax/cli#1384]
- [ 0.16.0] `eris version`

Hi, 
Im a little bit confused to create my epm.yaml file to deploy my smart contract. Could you give some help to prepare for this? Thank you

Here is the Smart contract.
------------------------------------------------------------------------------------------------------------
_pragma solidity ^0.4.4;

import "ConvertLib.sol";

contract TransferMoney{

address public owner;
mapping (address => uint) balances;

  function TransferMoney(){
    owner = msg.sender;
    balances[owner] = 2200;
  }

  function transfer (address _to, uint _value) returns (bool success){
    if(balances[msg.sender] < _value)
    {
      return false;
    }

    balances[msg.sender] -= _value;
    balances[_to] += _value;
    return true;
  }

  function getBalance(address _user) constant returns (uint _balance){
    return balances[_user];
  }
}

**Comment by zramsay** [comment]
hi @devfka you can get help from the community in the Slack (https://slack.monax.io). Issues are intended for bugs and new features rather than help writing applications.
