### ISSUE TITLE
is the apt repo down for https://apt.monax.io?

### ISSUE THREAD

**Issue by V-ess** [monax/cli#1408]
Please include in your bug report:

- [17.03.1-ce ] `docker version`
- [not installed yet ] `monax version`
- [ ] `go version` (if applicable)
- [n/a ] `docker-machine version` (if applicable / !linux)
- [xenial 16.04] operating system details (osx/windows/linux)
- [curl -L https://apt.monax.io/APT-GPG-KEY | sudo apt-key add - ] what you expected to happen
- [ curl: (6) Couldn't resolve host 'apt.monax.io'] what actually happened
- [ ] steps to reproduction

If issue is a feature request, tell us why this feature is useful.

**Comment by zramsay** [comment]
the URL changed to `pkgs.monax.io`; see the instructions on the website:
```
sudo add-apt-repository https://pkgs.monax.io/apt
curl -L https://pkgs.monax.io/apt/APT-GPG-KEY | sudo apt-key add -
sudo apt-get update && sudo apt-get install -y monax
```
