### ISSUE TITLE
"monax chains ls" does not work

### ISSUE THREAD

**Issue by levansuper** [monax/cli#1409]
Please include in your bug report:

- [17.05.0-ce, build 89658be] `docker version`
- [ 0.17.0] `monax version`
- [ 0.11.0, build 5b27455] `docker-machine version` (if applicable / !linux)
- [osx] operating system details (osx/windows/linux)
- [I am trying to list the chains with "monax chains ls"] what you expected to happen
- [I am getting 'Use "monax chains COMMAND --help" for more information about a command.' as if "ls does not exist"] what actually happened
- [just type "monax chains ls"] steps to reproduction

**Comment by levansuper** [comment]
<img width="753" alt="screen shot 2017-05-26 at 12 59 43" src="https://cloud.githubusercontent.com/assets/223112/26488182/6fe5076a-4213-11e7-955e-e76dd6bdf070.png">

**Comment by zramsay** [comment]
this command was removed (see [changelog](https://github.com/monax/cli/blob/master/CHANGELOG.md)). You can use `monax ls` in its place.

**Comment by levansuper** [comment]
Thanks for the response.
just to inform you I've been doing everything according to the tutorial so the info there is outdated.

**Comment by zramsay** [comment]
it's been updated on the site. sorry for the delay
