### ISSUE TITLE
[Core] Build shell integration 

### ISSUE THREAD

**Issue by compleatang** [monax/cli#39]
- [ ] bash completions.
- [ ] zsh package 

Namespace aliasing... `mintx` routing to `eris actions mintx do`...  Or to `docker run --volumes-from $(eris projects inspect data_container) eris/mintx` whatever. Need to consider flag conversion.

**Comment by compleatang** [comment]
http://stackoverflow.com/questions/3249432/i-have-a-bash-tab-completion-script-is-there-a-simple-way-to-use-it-from-zsh

**Comment by compleatang** [comment]
this isn't gonna happen just now. moving to 0.11

**Comment by compleatang** [comment]
zsh completions issue on dep lib -> https://github.com/spf13/cobra/issues/107

**Comment by koryk** [comment]
Was able to automatically generate a bash completion file by calling the  GenBashCompletionFile method on the ErisCmd object - https://godoc.org/github.com/spf13/cobra#Command.GenBashCompletionFile

The resulting file can be found here
https://gist.github.com/koryk/9b0625509def80cdefa451b61e8c9d25

**Comment by pietv** [comment]
Awesome! Thanks very much for this! :+1: Will play with this a little bit and integrate to Linux and Mac package generation. Automatic completion is so much better than the manual one; totally missed this Cobra functionality.

**Comment by zramsay** [comment]
obsolete
