### ISSUE TITLE
[Chains] logs -f behavior unexpected

### ISSUE THREAD

**Issue by slowtokyo** [monax/cli#612]
Command `eris chains logs [chain_name] -f` is expected to follow logs indefinitely. It stops following after 5-10 minutes.

**Comment by pietv** [comment]
@slowtokyo thanks for reporting the issue. Was this behaviour a single event or were you able reproduce it after you noticed it? Also, did you notice if the chain was still working while the `eris chains logs` stopped?

Tried to reproduce this behaviour on Linux and Mac with chains and 2 different services for about 30 min each — work as expected. Maybe you can come up with a better recipe for reproduction? Thanks!

**Comment by AFDudley** [comment]
is a temp file used?

**Comment by slowtokyo** [comment]
@pietv the chain was always still working when it happened before. I could get the logs to show noramlly again just by rerunning the command. I just rm all the chain containers and restarted everything yesterday. I'll let you know if I run into the problem again.

**Comment by slowtokyo** [comment]
Okay. Was just able to repeat it after ~3 minutes of running the logs. I can get the logs to run again after just rerunning the command. It has not effect on chain performance--i.e., I can still interact with teh chain through my dapp as expected. I suspect @AFDudley is right but not sure what it could be. 

To the extent that it's useful, I'm connecting into a digital ocean box in San Fran from Tokyo on a Macbook Air. Pinging the box is around 130m/s. At the rate that logs are generated, it might just not be able to keep up and hang after a few minutes?

**Comment by slowtokyo** [comment]
So when I ssh directly into the box and do `docker logs -f [container name]` it doesn't hang.

**Comment by slowtokyo** [comment]
Haha, so like a second after I posted that it hung! So probably still a resource constraint.

**Comment by pietv** [comment]
@slowtokyo Thanks for your experiments, very useful to know. Yes, indeed `logs -f` can choke on the logging output if the rate is too high (was able to reproduce this with a toy experiment). 

The potential fix would be to reduce the output to include only error events or display transaction information in a terser way, depending on what you're interested most (both ways would require amending erisdb).

**Comment by pietv** [comment]
Blocking on [#180](https://github.com/eris-ltd/eris-db/issues/180)

**Comment by zramsay** [comment]
the new logging coming to edb should help simplify logging options for cli

**Comment by zramsay** [comment]
will be address in #1262
