### ISSUE TITLE
[Keys] Checkout Keys Feature 

### ISSUE THREAD

**Issue by compleatang** [monax/cli#759]
**Problem** - - it's a PITA to do `addr=$(cat ~/.eris/chains/simplechain/accounts.csv | grep root_000 | cut - d ','  - f 1)` just to populate an address so I can run pkgs do. 

**Solution** - -  enable cli to populate address based on the csv and the account name. 

Since we require a chainName and this would be a convenience function, it should be quick, simple, helpful, and non-invasive.

**Comment by compleatang** [comment]
eris pkgs do should also understand key names when those are implemented here -> https://github.com/eris-ltd/eris-cli/issues/795

**Comment by zramsay** [comment]
to be discussed/decided in #969
