### ISSUE TITLE
[Keys] move eris-keys names functionality to eris keys (cli level)

### ISSUE THREAD

**Issue by compleatang** [monax/cli#795]
**Problem** -- the idea to have human readable names for keys was good. But currently we're managing that within the keys service's data container which we should be treating as more ephemeral. Keys that I actually want to give names to (maybe `caseyPersonal` or `ceoEris` key or whatever) I'll want to be safe on my host rather than in the containers. 

**Solution** -- 
- [ ] remove the eris-keys names functionality from eris-keys completely and move its logic and tests to cli level.
- [ ] add `eris keys names` for working with names. 
- [ ] think about how we can remove friction for users when they need/want specific keys loaded for specific chains or services.

**Comment by silasdavis** [comment]
This ticket is defunct, see: https://github.com/eris-ltd/eris-db/issues/336

**Comment by zramsay** [comment]
obsolete & not something we ought to focus on
