### ISSUE TITLE
[Core] Eris chains start simplechain does not restart old container and chain

### ISSUE THREAD

**Issue by infinius12345** [monax/cli#850]
Please include in your bug report:

infinius@infinius-VirtualBox:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
- [0.12.0-rc2] `eris version`
- [go version go1.6 linux/amd64
- [ Ubuntu 14.04 on virtual box] 
  infinius@infinius-VirtualBox:~$ eris chains start simplechain -v
  The marmots could not find docker-machine installed. While it is not required to use the Eris platform, we strongly recommend it be installed for maximum blockchain awesomeness.
  Booting chain dependencies             chains=[]
                                   services=[keys]
  Starting a chain                              simplechain
  Running container                             simplechain-10954a0e-21df-4207-b636-206e317962f5
  Manage data containers?              autodata=true
  Data container already exists. Not creating
  Starting container                            simplechain-10954a0e-21df-4207-b636-206e317962f5
                                        cmd=[run]
                             data container=simplechain-31cc220f-6b57-49b8-a126-ef0ac28c76f7
                                 entrypoint=[erisdb-wrapper]
                                environment=[CHAIN_ID=simplechain ERISDB_API=true]
                                      image=quay.io/eris/erisdb:0.12.0-rc2
                            published ports=false
  Container started                             simplechain-10954a0e-21df-4207-b636-206e317962f5
  infinius@infinius-VirtualBox:~$ eris chains ls
  CHAIN           ON     CONTAINER ID     DATA CONTAINER
  simplechain     -      c55e1be9cd       5e85b4042c

infinius@infinius-VirtualBox:~$ docker ps -a | grep c55e1be9cd
c55e1be9cdbc        quay.io/eris/erisdb:0.12.0-rc2   "erisdb-wrapper new"     11 days ago         Exited (1) 28 seconds ago                       simplechain-10954a0e-21df-4207-b636-206e317962f5

After restarting the OS i am unable to restart the chain. Is there a fix to it? i read old issues and it seems like it was fixed for 0.12.0 but why is it still happening to me ? are there more steps involved?

**Comment by pietv** [comment]
@infinius12345 thank you for reporting the issue! I wasn't able to reproduce this on Mac or Linux, but on Windows with VirtualBox driver I managed to came across a situation when I wasn't able to restart the chain I've created before restarting the VM. 

Based on that case, I'll try to figure out what's causing this and get back to you with a response.

**Comment by zramsay** [comment]
@infinius12345 Did you get this working? The process will be clearer and smoother in the upcoming release. Am closing for now. Please re-open if you are still running into problems.

**Comment by h0ryn** [comment]
Running into the exact same problem here - Windows VM

**Comment by zramsay** [comment]
@h0ryn do you still encounter this issue?

**Comment by zramsay** [comment]
closing as unresponsive.

**Comment by pietv** [comment]
The issue hasn't been addressed yet.

**Comment by compleatang** [comment]
closing as non-responsive
