### ISSUE TITLE
[Core] Add anonymized KPI tracking to eris-cli

### ISSUE THREAD

**Issue by compleatang** [monax/cli#851]
**Problem** -- we want to gain increased understanding of how people are using eris and where their problems are. This will allow us to more clearly make resourcing decisions as well as point to where we need to have effort in terms of cleaning things up.

**Solution** -- implement a two part KPI tracking system. 

**Strategy** -- Part A should focus on caching locally a few metrics to begin with (namely, number of times `chains make` is ran; number of times `pkgs do` is ran; number of `eris` commands typed along with error rates; and number of contracts which are compiled). These metrics can and should be cached locally in an agreed format (I would suggest a `~/.eris/scratch/usage.json`) which can in turn be consumed by Part B. 

Part B will require a KPI server which logs the reported metrics that are sent to it via cli users. The server should respect the current do_not_report setting in user's ~/.eris/eris.toml file. 

One key decision point is how often to report the usage metrics. I would suggest we add a `last_reported` field to the usage.json and if any eris commands are ran `>24hours` after that field, that we send the report. I can also see a case for `>7days` and a number of other intervals. I don't have strong opinions here, but ~daily feels about right to me. 

Another key decision point is whether to zero the usage metrics after reporting. Currently the goal would be to have increased understanding of overall eris usage while also respecting user's privacy. To that vein, if we zero the metrics after reporting then on the server side we can simply aggregate the metrics and not worry about having to track some delta. In order to properly track an individual user's delta, the only other way I can think about is to track locally both the overall, and the weekly delta both, and have cli only report the delta (which is complex for no reason). 

As this issue is going to cut across a few repositories, this will be an Epic, so will be easier for eris folks to track via Zenhub.

**Comment by pietv** [comment]
++ for once daily.
