### ISSUE TITLE
[Services] Warning feature request for logspout

### ISSUE THREAD

**Issue by slowtokyo** [monax/cli#875]
When starting logspout there is no warning if you have not set up the `logspout.toml` file with the proper routing beforehand--the container just doesn't start the service.

It would be good if there is a check for services that require configuration to throw a warning such as `Service is not properly configured and did not start. Please view your services .toml files to configure the service before attempting to start.` if they are not able to start properly.

**Comment by zramsay** [comment]
++ great idea. Will implement.

**Comment by zramsay** [comment]
cli only supports (out of the box) logrotate
