### ISSUE TITLE
[Pkgs] use checked out chains

### ISSUE THREAD

**Issue by compleatang** [monax/cli#886]
**Problem** -- currently eris pkgs do fails if no `--chain` flag is given to it. However, this is strictly speaking not right. We have the functionality of being able to "check out" a chain, which eris pkgs do should respect. 

**Solution** -- make the chain check piece become smarter. It should error if no flag is given && if no chain is checkedout || if the checkedout chain does not exist

**Comment by zramsay** [comment]
blocked by #969

**Comment by zramsay** [comment]
rejected per Slack discussion (IIRC). we'll do checked out keys
