### ISSUE TITLE
[Logging] have `--verbose` be more useful and less chatty

### ISSUE THREAD

**Issue by zramsay** [monax/cli#903]
**Problem:** `--verbose` is far too chatty and thus not all that useful as a `give-me-some-additional-information-for-the-otherwise-quiet-eris` that isn't _tons_ of debug output.

**Solution:**
`log.Info()` => `log.Debug()`
we may also want to consider deduplicating log messages, like #468

**Comment by pietv** [comment]
Definitely needs gleaning through the code to turn `Info` messages into `Debug` ones.

We actually have a guidilne about this already [CONTRIBUTING](https://github.com/eris-ltd/eris-cli/blob/master/.github/CONTRIBUTING.md):

I try to follow this whenever I can (dumps and variable/struct names go to `Debug`; additional info goes to `Info`), but there`s a lot left:
```
Use Info log level for optional messages software users somehow might benefit from (--verbose flag).
Use Debug log level for optional messages targeted at developers only (--debug flag).
```

> log.Info() => log.Warn()
You meant `log.Info` => `log.Debug`? Turning to `Warn` will make `eris` too chatty by default, which is not good.

**Comment by zramsay** [comment]
yeah, `log.Debug` is  what I meant. edited.

**Comment by zramsay** [comment]
painting the bike shed
