### ISSUE TITLE
[Services] requiring a network connection shutdown without throwing an error

### ISSUE THREAD

**Issue by slowtokyo** [monax/cli#910]
Please include in your bug report:
- [1.11.1 ] `docker version`
- [  0.12.0-rc3] `eris version`
- [ go1.7 ] `go version` (if applicable)
- [ 0.7.0] `docker-machine version` (if applicable / !linux)
- [ osx] operating system details (osx/windows/linux)
- [ when starting up a service like logspout that requires an internet connection the service starts and then immediately shuts down when it can't find a network connection. In this case an error explaining the situation should be thrown. ] what you expected to happen
- [ It looks like the service started without a problem but then when checking with `eris ls` the service is not actually running. ] what actually happened
- [ try running `eris services start logspout` without an internet connection ] steps to reproduction

**Comment by zramsay** [comment]
thanks for the bug report @slowtokyo
This is definitely a bug which we'll address in the near-term.

**Comment by slowtokyo** [comment]
Have a fix for this. Basically wait a second to see if the container times out and then throw an error informing the user that it shut down if it did time out. Will submit a PR.

**Comment by zramsay** [comment]
@slowtokyo did you have a chance to finish the PR you mentioned?

**Comment by slowtokyo** [comment]
No. I don't think I'll have much time for this until maybe mid-December but may be able to pick it up again after that.

**Comment by zramsay** [comment]
no longer part of the direction of the platform
